# Do not edit. Generated by the configure script.
export PATH:=/Users/Vikas/Documents/companyAssignment/newEnv/incubator-superset/node-v12.11.1/out/tools/bin:$(PATH)
PYTHON=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
BUILDTYPE=Release
PREFIX=/Users/Vikas/Documents/companyAssignment/newEnv
NODE_TARGET_TYPE=executable
